### ISSUE TITLE
The export process creates a GitHub Milestone

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/playbook#24]
Use repo: test-community

Milestone should have title, description and due_on populated. The default state of "Open" is fine.

See data mappings, etc. at https://sites.google.com/a/northbridgetech.org/2015-summer-internship/specifications/specifications

**Comment by goiaba** [comment]
Blake,

After our discussion yesterday, today I was able to create a Milestone into GitHub (using pygithub3) with the information gathered from our backlog table. The only different thing from what we were trying is that I added 'login' and 'password' information into the GitHub constructor (code below). Actually, I think this is really strange, because (1) this is not necessary when doing the same request using curl and (2) in the documentation of the Service class (base class for Milestones) they say:

"You can configure the **authentication** with BasicAuthentication (login and password) and with `OAuth <http://developer.github.com/v3/oauth/>`_ (token).
If you include ``login``, ``password`` and ``token`` in config; Oauth has precedence"

We can talk more about it today afternoon.

Code:
#====================================================
from pygithub3 import Github
import psycopg2
import psycopg2.extras

SELECTED_STATUS = 14

def createGHMilestone():
    config_file = open('CONFIG', 'r')
    token = config_file.readline()
    db = config_file.readline().rstrip()
    hst = config_file.readline().rstrip()
    usr = config_file.readline().rstrip()
    pswrd = config_file.readline().rstrip()
    config_file.close()
    
    stmt=('SELECT b.story_title, b.story_descr, e.end_dttm'
          '  FROM event e, backlog b'
          ' WHERE b.sprint_id_fk = e.id'
          '   AND b.status_id_fk = %s;')
    conn = psycopg2.connect(database=db, host=hst, user=usr, password=pswrd)
    cur = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)
    cur.execute(stmt, (SELECTED_STATUS,))
        
    gh = Github(token=token, login='<your_login>', password='<your_password>', user='NorthBridge', repo='test-community')
    
    for story_title, story_descr, end_dttm in cur:
        milestone = dict(title=story_title, description=story_descr, state="open", due_on=end_dttm)
        ghMilestone = gh.issues.milestones.create(milestone)
        print ghMilestone.number

createGHMilestone()
#====================================================
