### ISSUE TITLE
How correct is the project structure?

### ISSUE THREAD

**Issue by goiaba** [NorthBridge/playbook#32]
There is a core django app that contain the model classes and some code that could be shared amongst other apps.  There is also a specific django app to handle backlogs. The question is how correct is this structure and whether we should create a single app taking into account the low level of complexity of this project.

**Comment by hectron** [comment]
@goiaba , are you wondering if the `Playbook` project should be structured as a reusable app?

If so, I would suggest [checking out this excellent article](https://docs.djangoproject.com/en/1.8/intro/reusable-apps/) on how to properly structure a Django application to be reusable.

Based on some of the recommendations, the structure of `playbook` should be reconsidered. We're at an early stage where it can still be accomplished fairly quickly. If others approve this, I would be more than happy to assist you in doing this.

**Comment by kdflint** [comment]
It seems perfectly reasonable to restructure this project for reusability. Ideally this can turn into something that is of use to more than just Northbridge, and this isthe time to do that work.

Shall we raise this question tomorrow when we meet up with our new team?

**Comment by hectron** [comment]
Indeed, @kdflint . I think that a good structure can take the project very far. If it is brought up, I would be interested in working (or leading) the re-structure.

**Comment by kdflint** [comment]
Hector, I think Brad Martsburger will be reaching out to you on this.

Kathy

-- 



*Kathy Flint, CEO Northbridge Technology Alliance
http://northbridgetech.org
<http://NorthBridgeTech.org>kathy.flint@northbridgetech.org
<kathy.flint@northbridgetech.org> *

**Comment by martsberger** [comment]
Let's also make sure we're clear what reusability means here. A Django **project** is made from a collection of **apps**. Django itself has some apps built in, you can pull in third party apps, and write your own apps to make up your full project. A project is always reusable in the sense that it can be deployed on any number of web servers at any domain you like, each backed with it's own separate database. An app is reusable if it can be installed and used in another project separate from the project it is in.

I think it's clear that the project should be reusable by other teams/organizations, but we don't have to do anything special for that. It's not so clear to me that any of apps that we write for this project need to be made reusable. The question to answer is, would someone writing their own Django project benefit from reusing just the backlog (or core, etc.) app from this project? If the answer is yes, then we can consider the tradeoffs of making the individual app reusable.

There are drawbacks to making the apps reusable. (If I'm wrong on any of these please correct me).
* Each reusable app needs to live in its own project in its own repository.
* The apps should be completely decoupled.
* If we decouple the apps for reusability, we have to make API decisions now while there is still uncertainty.

I'm happy to work on structuring this however the team decides is best. My opinion at the moment is that the most important reusable piece for us is the project and making the individual apps reusable adds a level of overhead that will slow down development.

**Comment by hectron** [comment]
Hey @martsberger ,

I like that you identified the differences between a reusable **project** and an **app**. Both variations will provide a different outcome, and require different approaches. 

Based on the vision of this, I agree that it should be **production ready**. By this, I mean that it should be able to be downloaded, configured using custom settings (e.g. database credentials, API tokens, etc), and deployable.

When building the application, I do **not** think we should be concerned with making the apps be reusable. There might be overlapping functionality between two or more apps, in which case we might consider making the overlapping functionality a single app. This will become apparent as we start to work.

Some good directory structures include [_**Two Scoops of Django's recommended layout**_](https://github.com/twoscoops/django-twoscoops-project) and [_**Django-Kevin's recommended layout**_](https://github.com/imkevinxu/django-kevin). The latter goes into detail on how to set up more niche tools, but it's worth checking out.

**Comment by kdflint** [comment]
Good convo!  So, there are actually several modest functionalities that the volunteer ecosystem of Northbridge needs, and given this emerging discussion I think it would be helpful for me to lay out something of a broader picture.

For instance, in addition to backlog management problem which the current effort is targeted to address, I would also like to see a more full scale "portal" (to use an old-fashioned term) where teams have a central place to view the sprint calendar, find the link to their own conference room, bridge line, etc. Also, I would like every volunteer to have a place where their contributions are accumulating in some type of resume-friendly way: think source code commits, badges, time served, etc. And it would be quite cool if access to all these resources were driven through the GitHub authorization framework so that our actual user provisioning is all done through GH UI. (I don't know the technical details of what is possible there, I'm just trying to give a sense of things.)

Since understanding the end game is most important in these types of recommendations, by Wednesday I will outline the broader context of the needs of the Northbridge volunteer ecosystem. This way we can more intelligently define our broad design.

This will be useful, yes?

**Comment by hectron** [comment]
Hey @kdflint ,I think it would be very useful! Thanks for providing the outline. I'm super excited.

**Comment by kdflint** [comment]
This issue was moved to NorthBridge/alliance-community#12
