### ISSUE TITLE
Secrets should be kept in environment variables, not in settings.py

### ISSUE THREAD

**Issue by martsberger** [NorthBridge/playbook#55]
Things that are secret should not be kept in our repository, for example SECRET_KEY, DATABASES['USER'], DATABASES['PASSWORD'], DATABASES['HOST'], and DATABASES['PORT'] should be read from environment variables, e.g.,

```python
SECRET_KEY = os.environ.get('django_secret_key')

DATABASES = {
    default: {
        'USER': os.environ.get('DB_USER')
        'PASSWORD': os.environ.get('DB_PASSWORD')
        # etc.
    }
}
```

Then the project can be deployed in different environments (production, staging/dev, local development) without changing the code.

**Comment by foresmac** [comment]
Yes, this is absolutely critical from a security standpoint. Any current secrets or keys that are in the repository should immediately be revoked and new ones issued/created.

**Comment by hectron** [comment]
Hi guys,

Thanks for bringing this up. I'm taking care of this in the restructure.

Cheers,
h

**Comment by foresmac** [comment]
`DEBUG` should be set with an ENV too:

```python
DEBUG = True if os.getenv('DEBUG', 'false').lower() == 'true' else False
```
_Note:_ The way this is written, any of the following would be valid true values: `true`, `True`, `TRUE`.

**Comment by foresmac** [comment]
You should also be using `[dj_database_url](https://github.com/kennethreitz/dj-database-url)` to configure the database setting.

``` python
LOCAL_DB_IP = os.environ.get('SOME_ENV_DB_IP')

DATABASES = {
    'default': dj_database_url.config(
        default='postgres://postgres:postgres@{0}/postgres'.format(LOCAL_DB_IP)
    )
}
```
The default will connect to a local db assuming you set its IP as an ENV somewhere if `DATABASE_URL` is missing or blank; else it will read `DATABASE_URL` and generate a Django config for you.

**Comment by kdflint** [comment]
The pattern that we have followed for other Northbridge apps is to store normal env variables in a config file within the project. But then that config file points to another file which contains anything sensitive, like passwords.

The sensitive config file is NOT stored inside the project (or repo) and access is restricted by access to the server. 

The normal config file may be stored in the repo. if that is useful.

This is what we do in other projects...

**Comment by foresmac** [comment]
For Django projects, `settings.py` effectively _is_ your config file. I do keep a file locally with a list of ENV variables for staging and production (what you would call the "sensitive config file"), and most hosting platforms (we use AWS at work, but Google Cloud Platform, Heroku, whatever) have some method to inject ENV variables into your VM so I can copy and paste those as needed. That's pretty much standard devops procedure across the industry.

**Comment by hectron** [comment]
These are all valid points.

In the restructure, I created a way to inject different config files based on the environment you're in.

Furthermore, each of those calls from the environment's PATH.

Based on what @kdflint mentioned, I have an idea that can satisfy all of our concerns.

This is the current structure that I have:

![image](https://cloud.githubusercontent.com/assets/1649281/9529554/99156b1a-4cc0-11e5-888a-ee47c7c8cbb5.png)

The way the settings are loaded, there's a base `settings.py` that is inherited by {dev, test, prod}.py, then the settings in the `{dev, test, prod}.py` overrides the settings from `settings.py`. I make it such that `settings/dev.py` is in the `.gitignore` file, so that a developer's local settings are not accidentally pushed up. That way, they can hardcode whatever settings they need.

**Comment by kdflint** [comment]
This issue was moved to NorthBridge/alliance-community#10
